### PR TITLE
31 season statistics fewest tackles

### LINKED ISSUE #31: Season Statistics - fewest_tackles
Name of the Team with the fewest tackles in the season 
--
Return Value: String

### PR DESCRIPTION
**Pull request by aleish-m**
Fix #31 and refactor the helper method for #30 and #31

### CODE REVIEW

**Review by knestler — APPROVED** [review]

**Review by KevinT001 — DISMISSED** [review]
Almost to the end. looks good.

**Review by knestler — DISMISSED** [review]
merging these

**Review by stephenfabian — APPROVED** [review]
Thanks for the refactor!

**Review by KevinT001 — APPROVED** [review]
Re-approving after the merge conflict resolved

**Review by knestler — APPROVED** [review]

**Pull request merged**
